import yaml
from datetime import datetime, timezone

import rms_config

_cfg = rms_config.load()


def load_dag():
    """Load the hypothesis DAG from the path declared in research.yaml."""
    path = _cfg.dag_path
    if not path.is_file():
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def generate_mermaid_dag(dag):
    """
    Generate an enhanced Mermaid.js representation of the Hypothesis DAG.
    """
    if not dag: return ""
    nodes = dag.get('nodes', [])
    if not nodes: return ""

    mermaid = ["graph TD"]
    
    # 1. Define Nodes and Connections
    for node in nodes:
        node_id = node['id']
        label = f"{node_id}<br/>{node['status'].upper()}"
        
        # Add connections (Handle list or single parent)
        parents = node.get('parent', [])
        if isinstance(parents, str):
            mermaid.append(f"    {parents} --> {node_id}")
        elif isinstance(parents, list):
            for p in parents:
                mermaid.append(f"    {p} --> {node_id}")
        
        # Add shape and label
        mermaid.append(f'    {node_id}["{label}"]')

    # 2. Add Styling
    mermaid.append("\n    %% Styling Classes")
    mermaid.append("    classDef completed fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;")
    mermaid.append("    classDef discarded fill:#ffcdd2,stroke:#c62828,stroke-width:2px;")
    mermaid.append("    classDef pending fill:#fff9c4,stroke:#fbc02d,stroke-width:2px;")
    mermaid.append("    classDef validated fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;")
    mermaid.append("    classDef ineffective fill:#ffcdd2,stroke:#c62828,stroke-width:2px;")
    mermaid.append("    classDef framed fill:#e1bee7,stroke:#6a1b9a,stroke-width:2px;")
    mermaid.append("    classDef in_progress fill:#bbdefb,stroke:#1565c0,stroke-width:2px,stroke-dasharray: 5 5;")

    for node in nodes:
        status = node['status']
        mermaid.append(f"    class {node['id']} {status};")

    return "\n".join(mermaid)

def update_dashboard(dag):
    if not dag:
        print(f"Error: DAG not found at {_cfg.dag_path}")
        return

    mermaid_content = generate_mermaid_dag(dag)

    project = dag.get('project', {}) if isinstance(dag, dict) else {}
    header = f"""# Research Lineage Dashboard

> **Project**: {project.get('name', _cfg.dashboard_title)}
> **Objective**: {project.get('objective', 'No objective')}
> **Last Updated**: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}

---

## Hypothesis Lineage Graph

```mermaid
{mermaid_content}
```

---

## DAG Summary

| ID | Hypothesis | Status | Performance |
| :--- | :--- | :--- | :--- |
"""
    
    rows = ""
    for node in dag['nodes']:
        perf = node.get('performance') or node.get('actual_performance') or "-"
        rows += f"| {node['id']} | {node['hypothesis'][:80]}... | {node['status']} | {perf} |\n"

    active = "\n---\n\n## Active Research Strands\n\n"
    found_active = False
    for node in dag['nodes']:
        if node['status'] in ('framed', 'in_progress'):
            phase = "Designed" if node['status'] == 'framed' else "In progress"
            active += f"- **{node['id']}** ({phase}): Branch `{node.get('branch')}` (Agent: {node.get('assigned_agent')})\n"
            found_active = True
    if not found_active: active += "*No strands currently active.*\n"

    footer = "\n--- \n*Generated by RMS Housekeeper*"
    
    output_path = _cfg.dashboard_mermaid
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header + rows + active + footer)
    print(f"Updated {output_path} with current lineage.")

if __name__ == "__main__":
    dag = load_dag()
    update_dashboard(dag)
