import yaml
import os
import sys
from datetime import datetime

def load_dag(path='hypothesis-dag.yaml'):
    if not os.path.exists(path):
        # Check fallback
        if os.path.exists('docs/hypothesis-dag.yaml'):
            path = 'docs/hypothesis-dag.yaml'
        else:
            return None
    with open(path, 'r') as f:
        return yaml.safe_load(f)

def generate_mermaid_dag(dag):
    """
    Generate an enhanced Mermaid.js representation of the Hypothesis DAG.
    """
    if not dag: return ""
    nodes = dag.get('nodes', [])
    if not nodes: return ""

    mermaid = ["graph TD"]
    
    # 1. Define Nodes and Connections
    for node in nodes:
        node_id = node['id']
        label = f"{node_id}<br/>{node['status'].upper()}"
        
        # Add connections (Handle list or single parent)
        parents = node.get('parent', [])
        if isinstance(parents, str):
            mermaid.append(f"    {parents} --> {node_id}")
        elif isinstance(parents, list):
            for p in parents:
                mermaid.append(f"    {p} --> {node_id}")
        
        # Add shape and label
        mermaid.append(f'    {node_id}["{label}"]')

    # 2. Add Styling
    mermaid.append("\n    %% Styling Classes")
    mermaid.append("    classDef completed fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;")
    mermaid.append("    classDef discarded fill:#ffcdd2,stroke:#c62828,stroke-width:2px;")
    mermaid.append("    classDef pending fill:#fff9c4,stroke:#fbc02d,stroke-width:2px;")
    mermaid.append("    classDef validated fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;")
    mermaid.append("    classDef ineffective fill:#ffcdd2,stroke:#c62828,stroke-width:2px;")
    mermaid.append("    classDef framed fill:#e1bee7,stroke:#6a1b9a,stroke-width:2px;")
    mermaid.append("    classDef in_progress fill:#bbdefb,stroke:#1565c0,stroke-width:2px,stroke-dasharray: 5 5;")

    for node in nodes:
        status = node['status']
        mermaid.append(f"    class {node['id']} {status};")

    return "\n".join(mermaid)

def update_dashboard(dag):
    if not dag:
        print("Error: No DAG found.")
        return

    mermaid_content = generate_mermaid_dag(dag)

    header = f"""# Research Lineage Dashboard

> **Project**: {dag['project'].get('name', 'Unnamed')}  
> **Objective**: {dag['project'].get('objective', 'No objective')}  
> **Last Updated**: {datetime.utcnow().strftime('%Y-%m-%d')}

---

## Hypothesis Lineage Graph

```mermaid
{mermaid_content}
```

---

## DAG Summary

| ID | Hypothesis | Status | Performance |
| :--- | :--- | :--- | :--- |
"""
    
    rows = ""
    for node in dag['nodes']:
        perf = node.get('performance') or node.get('actual_performance') or "-"
        rows += f"| {node['id']} | {node['hypothesis'][:80]}... | {node['status']} | {perf} |\n"

    active = "\n---\n\n## Active Research Strands\n\n"
    found_active = False
    for node in dag['nodes']:
        if node['status'] in ('framed', 'in_progress'):
            phase = "Designed" if node['status'] == 'framed' else "In progress"
            active += f"- **{node['id']}** ({phase}): Branch `{node.get('branch')}` (Agent: {node.get('assigned_agent')})\n"
            found_active = True
    if not found_active: active += "*No strands currently active.*\n"

    footer = "\n--- \n*Generated by RMS Housekeeper*"
    
    # Write to a dashboard file in the root or docs
    with open('RESEARCH_DASHBOARD.md', 'w') as f:
        f.write(header + rows + active + footer)
    print("Updated RESEARCH_DASHBOARD.md with current lineage.")

if __name__ == "__main__":
    dag = load_dag()
    update_dashboard(dag)
