import yaml
import os
import sys

def load_dag(path='docs/research/hypothesis-dag.yaml'):
    if not os.path.exists(path):
        return None
    with open(path, 'r') as f:
        return yaml.safe_load(f)

def generate_mermaid_dag(dag):
    """
    Generate an enhanced Mermaid.js representation of the Hypothesis DAG.
    """
    if not dag: return ""
    nodes = dag.get('nodes', [])
    if not nodes: return ""

    mermaid = ["graph TD"]
    
    # 1. Define Nodes and Connections
    for node in nodes:
        node_id = node['id']
        label = f"{node_id}<br/>{node['status'].upper()}"
        
        # Add connections (Handle list or single parent)
        parents = node.get('parent', [])
        if isinstance(parents, str):
            mermaid.append(f"    {parents} --> {node_id}")
        elif isinstance(parents, list):
            for p in parents:
                mermaid.append(f"    {p} --> {node_id}")
        
        # Add shape and label
        mermaid.append(f'    {node_id}["{label}"]')
        
        # Add Link
        mermaid.append(f'    click {node_id} "./{node_id}/" "{node["hypothesis"][:50]}..."')

    # 2. Add Styling
    mermaid.append("\n    %% Styling Classes")
    mermaid.append("    classDef completed fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;")
    mermaid.append("    classDef discarded fill:#ffcdd2,stroke:#c62828,stroke-width:2px;")
    mermaid.append("    classDef pending fill:#fff9c4,stroke:#fbc02d,stroke-width:2px;")
    mermaid.append("    classDef in_progress fill:#bbdefb,stroke:#1565c0,stroke-width:2px,stroke-dasharray: 5 5;")

    for node in nodes:
        status = node['status']
        mermaid.append(f"    class {node['id']} {status};")

    return "\n".join(mermaid)

def update_readme(dag):
    if not dag:
        print("Error: No DAG found.")
        return

    mermaid_content = generate_mermaid_dag(dag)

    header = f"""# Research Hub: Project Dashboard

> **Project**: {dag['project']['name']}  
> **Objective**: {dag['project']['objective']}  
> **Last Updated**: 2026-02-28

---

## Hypothesis Lineage (Interactive Graph)

```mermaid
{mermaid_content}
```

> **Note**: Click on any node to navigate to its research strand folder.

---

## DAG Summary

| ID | Hypothesis | Status | Performance |
| :--- | :--- | :--- | :--- |
"""
    
    rows = ""
    for node in dag['nodes']:
        perf = node.get('performance') or node.get('actual_performance') or "-"
        rows += f"| {node['id']} | {node['hypothesis'][:80]}... | {node['status']} | {perf} |\n"

    active = "\n---\n\n## Active Research Strands\n\n"
    found_active = False
    for node in dag['nodes']:
        if node['status'] == 'in_progress':
            active += f"- **{node['id']}**: Working on branch `{node.get('branch')}` (Agent: {node.get('assigned_agent')})\n"
            found_active = True
    if not found_active: active += "*No strands currently in progress.*\n"

    footer = "\n--- \n*Generated by Housekeeper Agent*"
    
    with open('docs/research/README.md', 'w') as f:
        f.write(header + rows + active + footer)
    print("Updated docs/research/README.md with enhanced Mermaid visual.")

if __name__ == "__main__":
    dag = load_dag()
    update_readme(dag)
